// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbSot549s_7CQNxrdmpOxmKoUKavD0x1k',
    appId: '1:89422569405:web:3e11d5ff89d6b0c546fcd4',
    messagingSenderId: '89422569405',
    projectId: 'flutterpractice-6711a',
    authDomain: 'flutterpractice-6711a.firebaseapp.com',
    storageBucket: 'flutterpractice-6711a.firebasestorage.app',
    measurementId: 'G-92VXY40RHK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrbXJZbq-jXdWpuYPukaf2rR8yILw52S8',
    appId: '1:89422569405:android:c95bf5cc103cc9b646fcd4',
    messagingSenderId: '89422569405',
    projectId: 'flutterpractice-6711a',
    storageBucket: 'flutterpractice-6711a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwJd_e0j2r6Il7w8naNkk16SEDT6uLgDo',
    appId: '1:89422569405:ios:cbb103ef18da69f446fcd4',
    messagingSenderId: '89422569405',
    projectId: 'flutterpractice-6711a',
    storageBucket: 'flutterpractice-6711a.firebasestorage.app',
    iosBundleId: 'com.example.pasMobile11pplg110',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwJd_e0j2r6Il7w8naNkk16SEDT6uLgDo',
    appId: '1:89422569405:ios:cbb103ef18da69f446fcd4',
    messagingSenderId: '89422569405',
    projectId: 'flutterpractice-6711a',
    storageBucket: 'flutterpractice-6711a.firebasestorage.app',
    iosBundleId: 'com.example.pasMobile11pplg110',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbSot549s_7CQNxrdmpOxmKoUKavD0x1k',
    appId: '1:89422569405:web:6ff4809b72bbefa046fcd4',
    messagingSenderId: '89422569405',
    projectId: 'flutterpractice-6711a',
    authDomain: 'flutterpractice-6711a.firebaseapp.com',
    storageBucket: 'flutterpractice-6711a.firebasestorage.app',
    measurementId: 'G-J6H5WJ1QXE',
  );
}
